### ISSUE TITLE
cannot remove '.git': No such file or directory

### ISSUE THREAD

**Issue by TheLastCreation** [thmhoag/swgemu-docker#1]
doing docker-build for the first time

rm: cannot remove '.git': No such file or directory
ERROR: Service 'swgemu' failed to build: The command '/bin/sh -c rm .git' returned a non-zero code: 1

**Comment by cryptosig** [comment]
The cloned version of the github has only a link to the Core3 library. You have to issue a `git submodule update --init --recursive` to download the Core3 otherwise the Dockerfile tries to Copy an empty folder. You could also potentially put the command in your Dockerfile before the copy statement.
